# Generated by Django 5.1.15 on 2026-09-25 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_image_webp_variants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('delivery', models.CharField(choices=[('pickup', "Do'kondan olib ketish"), ('courier', 'Yetkazib berish')], default='pickup', max_length=10, verbose_name='Yetkazish')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Manzil')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('confirmed', 'Tasdiqlandi'), ('ready', 'Tayyor / yetkazilmoqda'), ('done', 'Bajarildi'), ('cancelled', 'Bekor qilindi')], default='new', max_length=10, verbose_name='Holat')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Jami')),
                ('language', models.CharField(default='uz', max_length=5)),
                ('telegram_sent', models.BooleanField(default=False, verbose_name='Telegramga yuborildi')),
                ('admin_note', models.TextField(blank=True, verbose_name='Ichki izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('color_name', models.CharField(max_length=50)),
                ('size_label', models.CharField(max_length=60)),
                ('sku', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('qty', models.PositiveSmallIntegerField(default=1, verbose_name='Soni')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productvariant', verbose_name='Variant')),
            ],
            options={
                'verbose_name': 'Buyurtma qatori',
                'verbose_name_plural': 'Buyurtma qatorlari',
            },
        ),
    ]
