# Generated by Django 5.1.15 on 2026-09-24 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nomi')),
                ('name_uz', models.CharField(max_length=60, null=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(max_length=60, null=True, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True)),
                ('min_age_months', models.PositiveSmallIntegerField(default=0, verbose_name='Yosh (oy) dan')),
                ('max_age_months', models.PositiveSmallIntegerField(default=216, verbose_name='Yosh (oy) gacha')),
                ('height_from_cm', models.PositiveSmallIntegerField(default=50, verbose_name="Bo'y (sm) dan")),
                ('height_to_cm', models.PositiveSmallIntegerField(default=182, verbose_name="Bo'y (sm) gacha")),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Yosh guruhi',
                'verbose_name_plural': 'Yosh guruhlari',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='brands/', verbose_name='Logo')),
                ('country', models.CharField(blank=True, max_length=60, verbose_name='Mamlakat')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Brend',
                'verbose_name_plural': 'Brendlar',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
                ('name_uz', models.CharField(max_length=50, null=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True)),
                ('hex_code', models.CharField(default='#000000', max_length=7)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Rang',
                'verbose_name_plural': 'Ranglar',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SizeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=60, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': "O'lcham tizimi",
                'verbose_name_plural': "O'lcham tizimlari",
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Rasm')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_title_uz', models.CharField(blank=True, max_length=160, null=True)),
                ('meta_title_ru', models.CharField(blank=True, max_length=160, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('meta_description_uz', models.CharField(blank=True, max_length=300, null=True)),
                ('meta_description_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='Ota kategoriya')),
                ('default_size_type', models.ForeignKey(blank=True, help_text="Yangi mahsulot qo'shganda avtomatik tanlanadi", null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.sizetype', verbose_name="Standart o'lcham tizimi")),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('material', models.CharField(blank=True, max_length=200, verbose_name='Material')),
                ('material_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Material')),
                ('material_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Material')),
                ('care_notes', models.CharField(blank=True, max_length=300, verbose_name='Parvarish')),
                ('care_notes_uz', models.CharField(blank=True, max_length=300, null=True, verbose_name='Parvarish')),
                ('care_notes_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Parvarish')),
                ('season', models.CharField(choices=[('all', 'Barcha fasl'), ('spring', 'Bahor'), ('summer', 'Yoz'), ('autumn', 'Kuz'), ('winter', 'Qish')], default='all', max_length=10, verbose_name='Fasl')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name="Narx (so'm)")),
                ('sale_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Chegirma narxi')),
                ('is_new', models.BooleanField(default=False, verbose_name='Yangi')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Bosh sahifada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_title_uz', models.CharField(blank=True, max_length=160, null=True)),
                ('meta_title_ru', models.CharField(blank=True, max_length=160, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('meta_description_uz', models.CharField(blank=True, max_length=300, null=True)),
                ('meta_description_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('age_groups', models.ManyToManyField(blank=True, related_name='products', to='products.agegroup', verbose_name='Yosh guruhlari')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand', verbose_name='Brend')),
                ('category', models.ForeignKey(help_text='Faqat eng pastki (2-daraja) kategoriya', limit_choices_to={'parent__isnull': False}, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Kategoriya')),
                ('size_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.sizetype', verbose_name="O'lcham tizimi")),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='Rasm')),
                ('alt', models.CharField(blank=True, max_length=160)),
                ('alt_uz', models.CharField(blank=True, max_length=160, null=True)),
                ('alt_ru', models.CharField(blank=True, max_length=160, null=True)),
                ('is_primary', models.BooleanField(default=False, verbose_name='Asosiy')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.color', verbose_name='Rang')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Rasm',
                'verbose_name_plural': 'Rasmlar',
                'ordering': ['-is_primary', 'sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='134, 28, 32, XL', max_length=20, verbose_name='Kod')),
                ('label', models.CharField(help_text='134 sm (8–9 yosh)', max_length=60, verbose_name="Ko'rsatiladigan nom")),
                ('label_uz', models.CharField(help_text='134 sm (8–9 yosh)', max_length=60, null=True, verbose_name="Ko'rsatiladigan nom")),
                ('label_ru', models.CharField(help_text='134 sm (8–9 yosh)', max_length=60, null=True, verbose_name="Ko'rsatiladigan nom")),
                ('age_from_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('age_to_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('size_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.sizetype')),
            ],
            options={
                'verbose_name': "O'lcham",
                'verbose_name_plural': "O'lchamlar",
                'ordering': ['size_type', 'sort_order'],
                'unique_together': {('size_type', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=50, unique=True, verbose_name='SKU')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Qoldiq')),
                ('price_override', models.DecimalField(blank=True, decimal_places=0, help_text="Bo'sh bo'lsa mahsulot narxi", max_digits=12, null=True, verbose_name='Alohida narx')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.color', verbose_name='Rang')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.size', verbose_name="O'lcham")),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variantlar',
                'ordering': ['color__sort_order', 'size__sort_order'],
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
