# Generated by Django 5.1.15 on 2026-09-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='large',
            field=models.ImageField(blank=True, editable=False, upload_to='products/%Y/%m/large/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='thumb',
            field=models.ImageField(blank=True, editable=False, upload_to='products/%Y/%m/thumb/'),
        ),
    ]
