# Generated by Django 5.1.15 on 2026-09-26 12:57

import django.db.models.deletion
from django.db import migrations, models


def reset_self_parents(apps, schema_editor):
    Category = apps.get_model("products", "Category")
    Category.objects.using(schema_editor.connection.alias).filter(
        parent_id=models.F("pk")
    ).update(parent_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_image_webp_variants'),
    ]

    operations = [
        # Do not restore corrupt relationships when rolling back.
        migrations.RunPython(reset_self_parents, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text="Faqat ichki kategoriyasi yo'q kategoriya (1- yoki 2-daraja)", limit_choices_to={'children__isnull': True}, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Kategoriya'),
        ),
    ]
